# Generated by Django 3.2 on 2021-05-07 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='appraisal_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meter',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
