# Generated by Django 3.2 on 2021-05-08 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_userinfo_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=32)),
                ('inventory_model', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('univalent', models.CharField(max_length=10)),
                ('order_number', models.CharField(max_length=32)),
                ('amount', models.CharField(max_length=32)),
                ('operating_user', models.CharField(max_length=32)),
            ],
        ),
    ]
